Backend with db
SiqiZheng94/Project-RestaurantManagementSystem pull request #1
Opened 2024-01-11 17:59 UTC by SiqiZheng94

2024-01-11 18:21 UTC, Paci94 approved these changes

2024-01-12 10:49 UTC, tejue approved these changes
LGTM... as far as I am able to evaluate :)

2024-01-12 10:49 UTC, tejue commented on backend/src/main/java/com/example/backend/entity/DishInCart.java
> +//    }
For a clean code you might want to delete this part :)

2024-01-12 11:42 UTC, MoinMarcell requested changes
You are missing Testing and mixing everything up. Try to use vertical slices and concentrate on one aspect firtst. And you need to rethink of namingconventions, there are not as good

2024-01-12 11:42 UTC, MoinMarcell commented on backend/src/main/java/com/example/backend/OrderingSysService.java
> +    }
Methodname 'pay'?

2024-01-12 11:42 UTC, MoinMarcell commented on backend/src/main/java/com/example/backend/OrderingSysService.java
> +    public void addDishInCart(DishInCartDTO dishInCartDTO) {
```suggestion
    public void addDishToCart(DishInCartDTO dishInCartDTO) {
```

Typo

2024-01-12 11:42 UTC, MoinMarcell commented on backend/src/main/java/com/example/backend/controller/AdminController.java
Why is it called admin controller? You are adding and getting dishes here

2024-01-12 11:42 UTC, MoinMarcell commented on backend/src/main/java/com/example/backend/controller/UserController.java
> +public class UserController {
Why ist it called user controller?

2024-01-12 11:42 UTC, MoinMarcell commented on backend/src/main/java/com/example/backend/entity/DishInCart.java
> +//    }
No comments in production

2024-01-12 11:42 UTC, MoinMarcell commented on backend/src/main/java/com/example/backend/entity/DishInCart.java
> +public class DishInCart {
wired name for a Cart, why dont call it just Cart?

2024-01-12 11:42 UTC, MoinMarcell commented on frontend/src/pages/AllDishes.tsx
Its almost empty, delete it

2024-01-15 08:39 UTC, MoinMarcell approved these changes
LGTM, hope you know what are you doing

2024-01-15 08:39 UTC, MoinMarcell commented on backend/pom.xml
> +		</dependency>
Wofür brauchst du die? Du sprichst keine externe API an

2024-01-15 08:39 UTC, MoinMarcell commented on backend/src/main/java/com/example/backend/entity/Dish.java
> +        String _id,
```suggestion
        String id,
```

2024-01-15 08:39 UTC, MoinMarcell commented on backend/src/main/java/com/example/backend/entity/DishInCart.java
> +    private String _id;
```suggestion
    private String id;
```

2024-01-15 08:39 UTC, MoinMarcell commented on backend/src/main/java/com/example/backend/entity/DishInCart.java
> +    }
Du nutzt doch lombok, warum hier noch mal einen setter?

2024-01-15 08:39 UTC, MoinMarcell commented on backend/src/main/java/com/example/backend/controller/UserController.java
> +    }
warum heißt die methode pay obwohl du hier was löschen möchtest?

2024-01-15 08:39 UTC, MoinMarcell commented on backend/src/main/java/com/example/backend/OrderingSysService.java
> +    }
warum heisst die methode buy obwohl du hier was löschen möchtest? Und bist du sicher das du ALLES löschen möchtest aus der Datenbank an diesem Punkt?

2024-01-15 08:39 UTC, MoinMarcell commented on backend/src/main/java/com/example/backend/OrderingSysService.java
> +    private final OrderRepo orderRepo;
3 REpos? Das solltest du aufteilen in 3 verschiedene repos mit einem jeweiligen service

2024-01-15 08:39 UTC, MoinMarcell commented on backend/src/main/java/com/example/backend/controller/AdminController.java
> +    private final OrderingSysService service;
Admin macht hier keinen Sinn und ist auch nicht korrekt. Der Controller müsste DishesController heißen, da du hier dishes verwaltest. Auch der OrderingSysService versteh ich an dieser Stelle nicht. Was hat das mit dishes zu tun?

2024-01-15 09:03 UTC, SiqiZheng94 commented on backend/src/main/java/com/example/backend/OrderingSysService.java
> +    }
when the user clicks the pay button, the cart will be emptied and the bill will be created. An additional method will be added to the "pay" method that will calculate the bill. method name can be changed to "buy".

2024-01-15 09:03 UTC, SiqiZheng94 commented on backend/src/main/java/com/example/backend/controller/UserController.java
> +public class UserController {
As a user, you can add different dishes to the cart and check the dishes in the cart or manage the dishes in the cart in the future.
In contrary an admin is able to add new dishes to the menu and change the properties of a dish.

2024-01-15 09:03 UTC, SiqiZheng94 commented on backend/src/main/java/com/example/backend/controller/AdminController.java
I want to have two controllers, one for admin and one for users. the admin can add new dishes and manage existing dishes. this function will be added in future contributions.

2024-01-15 09:03 UTC, SiqiZheng94 commented on backend/src/main/java/com/example/backend/entity/DishInCart.java
> +public class DishInCart {
I designed DishToCart as an entity. and DishToCart DTO holds the information for dishes added to the cart and their amount. when the user clicks the "add" button, the DishInCart DTO includes the dishID and the amount of that dish is sented to the backend.

2024-01-15 12:05 UTC, merged